name: "nix-build"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v14.1
    - uses: cachix/cachix-action@v10
      with:
        name: utdemir
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
